import type { Transaction } from "./types"

export const EXAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: "ex-001",
    date: "2026-02-20",
    amount: 420,
    currency: "USD",
    description: "LemFi Transfer to Lagos - Adunni term fees",
    recipient: "Adunni Okafor",
    purpose: "Education",
    tags: ["education", "recurring"],
    source: "LemFi",
  },
  {
    id: "ex-002",
    date: "2026-02-14",
    amount: 200,
    currency: "USD",
    description: "LemFi Transfer to Accra - monthly upkeep",
    recipient: "Kwame Mensah",
    purpose: "Family",
    tags: ["family", "monthly"],
    source: "LemFi",
  },
  {
    id: "ex-003",
    date: "2026-02-01",
    amount: 550,
    currency: "USD",
    description: "WorldRemit to Nairobi - stock purchase",
    recipient: "Grace Wanjiku",
    purpose: "Business",
    tags: ["business"],
    source: "WorldRemit",
  },
  {
    id: "ex-004",
    date: "2026-01-28",
    amount: 150,
    currency: "USD",
    description: "LemFi Transfer to Lagos - food & essentials",
    recipient: "Adunni Okafor",
    purpose: "Family",
    tags: ["family", "recurring"],
    source: "LemFi",
  },
  {
    id: "ex-005",
    date: "2026-01-20",
    amount: 300,
    currency: "USD",
    description: "Wise Transfer to Kampala - January rent",
    recipient: "Joseph Mukasa",
    purpose: "Rent",
    tags: ["housing", "monthly"],
    source: "Wise",
  },
  {
    id: "ex-006",
    date: "2026-01-10",
    amount: 100,
    currency: "USD",
    description: "LemFi Transfer to Accra - clinic visit",
    recipient: "Kwame Mensah",
    purpose: "Medical",
    tags: ["health"],
    source: "LemFi",
  },
  {
    id: "ex-007",
    date: "2025-12-22",
    amount: 250,
    currency: "USD",
    description: "WorldRemit to Nairobi - stock reorder",
    recipient: "Grace Wanjiku",
    purpose: "Business",
    tags: ["business", "recurring"],
    source: "WorldRemit",
  },
  {
    id: "ex-008",
    date: "2025-12-15",
    amount: 500,
    currency: "USD",
    description: "LemFi Transfer to Lagos - term 1 fees",
    recipient: "Adunni Okafor",
    purpose: "Education",
    tags: ["education", "term-payment"],
    source: "LemFi",
  },
  {
    id: "ex-009",
    date: "2025-12-05",
    amount: 180,
    currency: "USD",
    description: "Wise Transfer to Kampala - Dec rent",
    recipient: "Joseph Mukasa",
    purpose: "Rent",
    tags: ["housing", "monthly"],
    source: "Wise",
  },
  {
    id: "ex-010",
    date: "2025-11-30",
    amount: 75,
    currency: "USD",
    description: "LemFi Transfer to Accra - Ama birthday gift",
    recipient: "Ama Asante",
    purpose: "Gift",
    tags: ["gift", "birthday"],
    source: "LemFi",
  },
  {
    id: "ex-011",
    date: "2025-11-18",
    amount: 650,
    currency: "USD",
    description: "WorldRemit to Nairobi - hospital emergency",
    recipient: "Grace Wanjiku",
    purpose: "Emergency",
    tags: ["emergency", "medical"],
    source: "WorldRemit",
  },
  {
    id: "ex-012",
    date: "2025-11-10",
    amount: 200,
    currency: "USD",
    description: "LemFi Transfer to Lagos - monthly upkeep",
    recipient: "Adunni Okafor",
    purpose: "Family",
    tags: ["family", "monthly"],
    source: "LemFi",
  },
  {
    id: "ex-013",
    date: "2025-10-25",
    amount: 300,
    currency: "USD",
    description: "Wise Transfer to Kampala - Oct rent",
    recipient: "Joseph Mukasa",
    purpose: "Rent",
    tags: ["housing", "monthly"],
    source: "Wise",
  },
  {
    id: "ex-014",
    date: "2025-10-15",
    amount: 350,
    currency: "USD",
    description: "LemFi Transfer to Lagos - school books",
    recipient: "Adunni Okafor",
    purpose: "Education",
    tags: ["education"],
    source: "LemFi",
  },
  {
    id: "ex-015",
    date: "2025-10-05",
    amount: 120,
    currency: "USD",
    description: "LemFi Transfer to Accra - monthly stipend",
    recipient: "Kwame Mensah",
    purpose: "Family",
    tags: ["family", "monthly"],
    source: "LemFi",
  },
  {
    id: "ex-016",
    date: "2025-09-28",
    amount: 400,
    currency: "USD",
    description: "WorldRemit to Nairobi - business expansion",
    recipient: "Grace Wanjiku",
    purpose: "Business",
    tags: ["business"],
    source: "WorldRemit",
  },
  {
    id: "ex-017",
    date: "2025-09-15",
    amount: 175,
    currency: "USD",
    description: "Wise Transfer to Kampala - savings deposit",
    recipient: "Joseph Mukasa",
    purpose: "Savings",
    tags: ["savings"],
    source: "Wise",
  },
  {
    id: "ex-018",
    date: "2025-09-01",
    amount: 225,
    currency: "USD",
    description: "Remitly Transfer to Harare - aunt medical",
    recipient: "Tendai Moyo",
    purpose: "Medical",
    tags: ["health", "family"],
    source: "Remitly",
  },
]
